# Generated by Django 3.1 on 2020-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lauch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=100)),
                ('flight_number', models.IntegerField()),
                ('launch_year', models.IntegerField()),
                ('launch_date_utc', models.CharField(max_length=100)),
                ('launch_date_local', models.CharField(max_length=100)),
                ('rocket_id', models.CharField(max_length=100)),
                ('rocket_name', models.CharField(max_length=100)),
                ('rocket_type', models.CharField(max_length=100)),
                ('land_success', models.BooleanField()),
                ('landing_vehicle', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('launch_success', models.BooleanField()),
            ],
        ),
    ]
