# Generated by Django 3.1 on 2020-09-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lauch',
            new_name='Launch',
        ),
    ]
