# Generated by Django 3.1 on 2020-09-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200901_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='flight_number',
        ),
    ]
