# Generated by Django 3.1 on 2020-09-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_launch_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='land_success',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_success',
            field=models.CharField(max_length=50),
        ),
    ]
